# Generated by Django 4.1.2 on 2024-07-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosapp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
