# Generated by Django 4.1.2 on 2024-07-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosapp', '0002_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
