# Generated by Django 4.1.2 on 2024-07-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosapp', '0003_remove_usuario_is_active_usuario_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
